// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCidIHEZa5t3eGmE0ynfb1e94PALpskSTI',
    appId: '1:708089436508:web:751d34e65d069f8750c999',
    messagingSenderId: '708089436508',
    projectId: 'bitfit102',
    authDomain: 'bitfit102.firebaseapp.com',
    storageBucket: 'bitfit102.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgT0w9jtIA1ij0yGai7SUu2VGvbFyX2IQ',
    appId: '1:708089436508:android:5928545468347f8550c999',
    messagingSenderId: '708089436508',
    projectId: 'bitfit102',
    storageBucket: 'bitfit102.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZJWPgKg8udpsJAX1DqsNiTvoamygOw_M',
    appId: '1:708089436508:ios:7046ab03daf0e61150c999',
    messagingSenderId: '708089436508',
    projectId: 'bitfit102',
    storageBucket: 'bitfit102.appspot.com',
    iosClientId: '708089436508-3uos1efnk8j3489ec92d70n2l8k3jg0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitfit102',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZJWPgKg8udpsJAX1DqsNiTvoamygOw_M',
    appId: '1:708089436508:ios:5eb6510032d8aca350c999',
    messagingSenderId: '708089436508',
    projectId: 'bitfit102',
    storageBucket: 'bitfit102.appspot.com',
    iosClientId: '708089436508-t769ag5f9k6tb39modkb4qjnhvt6pebu.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitfit102.RunnerTests',
  );
}
